name: kudosapp
description: A new Flutter application.

version: 0.0.2+6

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localization

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

  # system

  uuid: ^2.0.4

  path: ^1.6.4

  semaphore: ^0.1.4

  rxdart: ^0.24.0

  event_bus: ^1.1.1

  sprintf: ^5.0.0

  sortedmap: ^0.4.2+1

  sorted_list: ^0.1.0

  mutex: ^1.1.0

  equatable: ^1.1.1

  # core

  provider: ^4.1.3

  get: ^3.13.2

  get_it: ^5.0.1

  # firebase

  firebase_core: "^0.5.0+1"

  cloud_firestore: ^0.14.1+3

  firebase_storage: ^4.0.1

  firebase_messaging: ^7.0.3

  firebase_crashlytics: ^0.2.1+1

  firebase_analytics: ^6.0.2

  # auth

  firebase_auth: ^0.18.1+2

  google_sign_in: ^4.5.4

  # images

  cached_network_image: ^2.2.0+1

  image_picker: ^0.6.7+4

  flutter_svg: ^0.19.0

  flutter_cache_manager: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

# https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl
flutter_intl:
  enabled: true

flutter_icons:
  image_path_ios: "assets/icons/app_icon.png"
  image_path_android: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon_transparent.png"
  adaptive_icon_background: "assets/icons/app_icon_gradient.png"
  android: true
  ios: true
