name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  flutter_version: "1.17.5"
  java_version: "12.x"

jobs:
  tests:
    if: ${{ false }} # disabled
    name: Tests
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Cache flutter
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}

      - name: Use flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Install app dependencies
        run: flutter pub get

      - name: Running tests
        run: flutter test

  build_dart:
    name: Build Dart code
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}

    - name: Use flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}

    - name: Install app dependencies
      run: flutter pub get

    - name: Build
      run: flutter build aot

  build_android:
    if: ${{ false }} # disabled
    name: Build Android
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}

    - name: Cache flutter
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}

    - name: Use flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}

    - name: Install app dependencies
      run: flutter pub get

    - name: Add google-services.json
      run: |
        echo "$FIREBASE_CONFIG" > android/app/google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.android_google_services }}

    - name: Build Android app
      run: flutter build apk --debug

  build_ios:
    if: ${{ false }} # disabled
    name: Build iOS
    needs: [tests]
    defaults:
      run:
        working-directory: src
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}

    - name: Cache flutter
      uses: actions/cache@v1
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}

    - name: Use flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}

    - name: Cache Pods dependencies
      uses: actions/cache@v1
      with:
        path: ios/Pods
        key: ${{ runner.OS }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-pods-

    - name: Install app dependencies
      run: flutter pub get

    - name: Add GoogleService-Info.plist
      run: |
        echo "$FIREBASE_CONFIG" > ios/Runner/GoogleService-Info.plist
      env:
        FIREBASE_CONFIG: ${{ secrets.ios_google_services }}

    - name: Build
      run: flutter build ios --debug --no-codesign
